bump_version: null
lint: {}
nf_core_version: 3.0.1
org_path: null
repository_type: pipeline
template:
  author: Christopher Hakkaart
  description: Nanopore basecalling pipeline
  force: true
  is_nfcore: true
  name: nanobasecall
  org: nf-core
  outdir: .
  skip_features: []
  version: 1.0.0dev
update: null
